version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TeamA/TeamA.csproj
  build:
    commands:
    - echo Build started on `date`
    - dotnet publish -c release -o ./build_output TeamA/TeamA.csproj
    - aws cloudformation package --template-file app-sam.yaml --s3-bucket ccl-training --output-template-file app-output_sam.yaml    
artifacts:
  files:
    - app-output_sam.yaml   
  discard-paths: yes